### ISSUE TITLE
opentimsr -- setup_bruker_so() support for MacOS

### ISSUE THREAD

**Issue by lingjuewang** [michalsta/opentims#17]
Hi there,

Thanks for supporting such a great interface for accessing TIMS data.

I have been using R as my processing language. Just wondering whether there is an upcoming option to use this Bruker API on MacOS system. Any update would be appreciated. :)

Kind regards,
Mike

**Comment by MatteoLacki** [comment]
Hello,

I will try to bring this up on another meeting with Bruker [in 2 weeks].
Unfortunately, I think that it might altogether take time: it's a company and they are very busy and the SDK is not easily modularizable according to them.
What we could try out is to do it ourselves and convince them to use our code: that's likely the way to make it happen faster.

It would make a lot of sense to have it running on MacOS given the big changes in M1 and M2 architectures at relatively cheep price.

Best wishes,

**Comment by assafkacen1** [comment]
Any progress with Bruker so support for arm architecture?

**Comment by MatteoLacki** [comment]
Unfortunately no: Bruker guys have other priorities.
I assume that you want it for your own use, not as a product available only on macs?
In that case, simply running it through [UTM](https://mac.getutm.app/) should do the trick.

I sort of understand Bruker that Linux & Windows are most important.
I don't understand why they keep closed source and this way make it difficult to simply take their code and recompile it onto a given architecture.

So, sorry, but I don't think this is coming any time soon.
