### ISSUE TITLE
 timsTOF fleX supported?

### ISSUE THREAD

**Issue by nathemie** [michalsta/opentims#3]
We would like to approach a set of timsTOF FleX diaPASEF data from scratch. We are wondering if `opentims` works on the timsTOF fleX data, such that the`opentims_bruker_bridge` libraries can be also applied to TimsTOF FleX data? A Flex's .d folder  contains an analysis.tsf_bin as the data file, but not an analysis.tdf as usual in Pro data.
We got this error:`no such table: Frames` if read a FleX's .d
(We tested timsTOF Pro data using timsr and it worked)

**Comment by MatteoLacki** [comment]
Hi,

It depends on how Bruker designed the analysis.tsf_bin.
I will ask them Friday during our biweekly meeting with them.

Cheers!

*Mateusz Krzysztof Łącki*

*German tel. +49 159 01681376*
Polish tel. +48 579 647 311
Skype:   mathewin
GitHub: MatteoLacki <https://github.com/MatteoLacki>

**Comment by MatteoLacki** [comment]
Hi,

This is a different format and it was not meant to be supported by
timspy/opentims which is meant to deal with timstof pro devices only.
We might consider at some point asking Bruker for letting us know how to
deal with this format, but this is not coming within the next few months
for sure, sorry.
You should check, however, if they do not offer an SDK on their website.

Best wishes,

**Comment by nathemie** [comment]
OK. Thanks for the inquiry. We will try for other solutions.
