### ISSUE TITLE
ImportError after Pyintaller packaging

### ISSUE THREAD

**Issue by nathemie** [michalsta/opentims#8]
We used Pyinstaller to package our python based programs including timspy to process diaPASEF file into a binary executable file, however, we got these errors if we run the packaged binary. 
![image](https://user-images.githubusercontent.com/51101922/132379549-fbddd65c-e878-42d6-b2aa-d376b6b2e393.png)
Could you please help have a look at of these errors? We packaged sqlite3 but the errors seem still come from sqlite3.

**Comment by michalsta** [comment]
Okay, so this is quite complicated. I didn't have the time to play with PyInstaller+opentimspy combo yet, but you might get some luck trying the prerelease version of opentimspy (...a7 I think it is now) - we changed the build system a bit, which might resolve your issue. Or make it even worse ;) please report if it works, and if not I'll look into this further. I guess pyinstaller is something we would ultimately like to support...

**Comment by nathemie** [comment]
we recompiled the .so libraries and now it worked. Thanks for your suggestion anyway. All the best.
